name: 02 - Eventos
on: 
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * *' # Todos os dias las 7h UTC
  workflow_dispatch:
# Modificacion para ver ramas
jobs:
    echo:
        runs-on: ubuntu-latest 
        steps:
          - name: ShowTrigger
            run: 'echo "Event name: ${{ github.event_name }}"'