name: "Events"
on:
 push:
 pull_request:
 schedule:
    - cron: "55 17 * * *"
 workflow_dispatch:

jobs:
    job1:
        name: "job-events"
        runs-on: ubuntu-latest
        steps:
            - name: "ShowTrigger"
              run: |
               echo "Event name: ${{ github.event_name }}"

